### ISSUE TITLE
cell magic for C# (%%csharp) is missing from Juputer notebook version 6.1.3

### ISSUE THREAD

**Issue by CBrauer** [ewinnington/noteb#1]
Hello,

When I do "%lsmagic" I do not see a csharp kernel.  How can I install it?

Charles

**Comment by ewinnington** [comment]
Hello, are you trying to run these locally? To do so, you need to install the dot net kernel for jupyter. 

This blog post was done a few months ago with the dot-net try, I haven’t updated for the new dot net interactive. 

http://ewinnington.github.io/posts/jupyter-notebook-csharp-r

You can check you have a C# kernel installed with:

Now get the list of installed jupyter kernels: 

jupyter kernelspec list

Available kernels:
  c:\program files (x86)\microsoft visual studio\shared\python37_64\share\jupyter\kernels\python3 

Install the latest version of .net try

dotnet tool install dotnet-try -g

finally install the .net kernel for jupyter with the command: 

dotnet try jupyter install

test the kernel is now installed with 

jupyter kernelspec list

You can also see how it was installed in the dockerfile here: 

https://github.com/ewinnington/noteb/blob/master/Dockerfile

And test c# with jupyter in the browser with this example that is hosted online (it takes a minute to start the docker) 

https://mybinder.org/v2/gh/ewinnington/noteb/master?filepath=SqliteInteraction.ipynb

Sorry for formatting, on mobile.

**Comment by ewinnington** [comment]
Also newer instructions for jupyter & c# can be found here: 

https://github.com/dotnet/interactive/blob/main/docs/NotebooksLocalExperience.md

**Comment by ewinnington** [comment]
Please let me know if that was enough for you to resolve the issue, and I'll close it. If you need any additional help let me know.

**Comment by CBrauer** [comment]
I did all the steps you suggested, and now cell magic is broken. Here is a screen capture of my notebook:
 
![image](https://user-images.githubusercontent.com/1317234/92063453-fe210e80-ed4f-11ea-85b7-50e1d3f19e88.png)

**Comment by ewinnington** [comment]
I would suggest reaching out to the .net interactive team on their GitHub with the full list of installed csharp kernel and Jupyter notebook in an issue.

**Comment by CBrauer** [comment]
I don’t see “%%csharp” in any cell in any of your examples.

**Comment by ewinnington** [comment]
I don't understand what you are asking me to do here. Sorry.
